[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jarvis_db"
version = "0.1.32"
dependencies = [
    "SQLAlchemy",
    "pydantic",
    "jorm @ git+https://github.com/PickAim/jorm.git@v.0.1.29",
]
